export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":""},["/README.md"]],
  ["v-9609cf9c","/docs/blogs/myself/AboutMe.html",{"title":"关于我"},[":md"]],
  ["v-152a14b5","/docs/blogs/other/guide.html",{"title":"vuepress-theme-reco"},[":md"]],
  ["v-1abe23ea","/docs/books/DataBase/MySQL.html",{"title":"MySQL"},[":md"]],
  ["v-40ce00b2","/docs/books/DataBase/Redis.html",{"title":"Redis"},[":md"]],
  ["v-850662ac","/docs/books/Front/JS.html",{"title":"JavaScript"},[":md"]],
  ["v-6309c198","/docs/books/Front/TS.html",{"title":"TypeScript"},[":md"]],
  ["v-0dddf66c","/docs/books/Java/Java.html",{"title":"Java"},[":md"]],
  ["v-36e95dd0","/docs/books/Java/Java8.html",{"title":"Java8新特性"},[":md"]],
  ["v-6fb037a4","/docs/books/Java/JUC.html",{"title":"JUC"},[":md"]],
  ["v-0e1e95a5","/docs/books/Java/JVM.html",{"title":"JVM"},[":md"]],
  ["v-b1a00202","/docs/books/Java/Spring.html",{"title":"Spring"},[":md"]],
  ["v-24752fa6","/docs/books/Java/SpringBoot.html",{"title":"SpringBoot"},[":md"]],
  ["v-4f5a2179","/docs/books/Java/SpringMVC.html",{"title":"SpringMVC"},[":md"]],
  ["v-50fdcbab","/docs/books/theme-reco/api.html",{"title":"api"},[":md"]],
  ["v-ba135fa4","/docs/books/theme-reco/home.html",{"title":"theme-reco"},[":md"]],
  ["v-3242455a","/docs/books/theme-reco/plugin.html",{"title":"plugin"},[":md"]],
  ["v-379b6b48","/docs/books/theme-reco/theme.html",{"title":"theme"},[":md"]],
  ["v-0fca36fe","/docs/blogs/category1/2018/121501.html",{"title":"first page in category1"},[":md"]],
  ["v-0c2a5e1c","/docs/blogs/category1/2019/092101.html",{"title":"second page in category1"},[":md"]],
  ["v-1153e7ca","/docs/blogs/category2/2016/121501.html",{"title":"first page in category2"},[":md"]],
  ["v-1893998e","/docs/blogs/category2/2017/092101.html",{"title":"second page in category2"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
